### ISSUE TITLE
[Bug] ValueError with text from a reference

### ISSUE THREAD

**Issue by thoppe** [lipoja/URLExtract#30]
What a great library! I'm parsing PDF -> text files from the arXiv and a common motif that crashes the program is shown in this minimal example below:

``` python
from urlextract import URLExtract
extractor = URLExtract()

text = "et.al.[10]"
extractor.find_urls(text)
```

with the traceback

```
Traceback (most recent call last):
  File "failure.py", line 5, in <module>
    extractor.find_urls(text)
  File "/home/hoppeta/.pyenv/versions/3.6.0/lib/python3.6/site-packages/urlextract/urlextract_core.py", line 756, in find_urls
    return list(urls)
  File "/home/hoppeta/.pyenv/versions/3.6.0/lib/python3.6/site-packages/urlextract/urlextract_core.py", line 739, in gen_urls
    tmp_url = self._complete_url(text, offset + tld_pos, tld)
  File "/home/hoppeta/.pyenv/versions/3.6.0/lib/python3.6/site-packages/urlextract/urlextract_core.py", line 560, in _complete_url
    if not self._is_domain_valid(complete_url, tld):
  File "/home/hoppeta/.pyenv/versions/3.6.0/lib/python3.6/site-packages/urlextract/urlextract_core.py", line 632, in _is_domain_valid
    host = url_parts.gethost()
  File "/home/hoppeta/.pyenv/versions/3.6.0/lib/python3.6/site-packages/uritools/split.py", line 157, in gethost
    raise ValueError('Invalid host %r' % host)
ValueError: Invalid host 'et.al.[10]'
```

**Comment by lipoja** [comment]
Thank you for using this library. And bigger THANKS for reporting this issue! I will check it and try to fix it soon.

**Comment by dominikstraessle** [comment]
I've got the same issue with the following error message:
```python
ValueError                                Traceback (most recent call last)
<ipython-input-158-447ea8a54a6f> in <module>()
      1 text = '[img: http://www.newsisfree.com/images/fark/smh.com.au.gif ([smh.com.au])]'
----> 2 urls = list(set(url_extractor.find_urls(text)))
      3 urls

~/.local/lib/python3.6/site-packages/urlextract/urlextract_core.py in find_urls(self, text, only_unique)
    754         urls = self.gen_urls(text)
    755         urls = set(urls) if only_unique else urls
--> 756         return list(urls)
    757 
    758     def has_urls(self, text):

~/.local/lib/python3.6/site-packages/urlextract/urlextract_core.py in gen_urls(self, text)
    737             validated = self._validate_tld_match(text, tld, offset + tld_pos)
    738             if tld_pos != -1 and validated:
--> 739                 tmp_url = self._complete_url(text, offset + tld_pos, tld)
    740                 if tmp_url:
    741                     yield tmp_url

~/.local/lib/python3.6/site-packages/urlextract/urlextract_core.py in _complete_url(self, text, tld_pos, tld)
    558         complete_url = self._remove_enclosure_from_url(
    559             complete_url, tld_pos-start_pos, tld)
--> 560         if not self._is_domain_valid(complete_url, tld):
    561             return ""
    562 

~/.local/lib/python3.6/site-packages/urlextract/urlextract_core.py in _is_domain_valid(self, url, tld)
    630         # <scheme>://<authority>/<path>?<query>#<fragment>
    631 
--> 632         host = url_parts.gethost()
    633         if not host:
    634             return False

~/.local/lib/python3.6/site-packages/uritools/split.py in gethost(self, default, errors)
    155             return _ip_literal(host[1:-1])
    156         elif host.startswith(self.LBRACKET) or host.endswith(self.RBRACKET):
--> 157             raise ValueError('Invalid host %r' % host)
    158         # TODO: faster check for IPv4 address?
    159         return _ipv4_address(host) or uridecode(host, 'utf-8', errors).lower()

ValueError: Invalid host 'smh.com.au]'
```
Code:
```python
text = '[img: http://www.newsisfree.com/images/fark/smh.com.au.gif ([smh.com.au])]'
urls = list(set(url_extractor.find_urls(text)))
urls
```

I'm using Python 3.6.5 and IPython 6.4.0

**Comment by lipoja** [comment]
@dominikstraessle Hi, could tell me what version of urlextract are you using? I can not reproduce your error with the provided text and current version (0.9) of urlextract.

**Comment by lipoja** [comment]
Issue should be fixed, I've added both text to tests files. 

@thoppe Right now urlextract does not return text "et.al.[10]" as URL. If you are parsing something specific you might use your own settings that fit your needs. For example by setting the stop characters using `set_stop_chars_right` and `set_stop_chars_left`.

**Comment by thoppe** [comment]
Awesome! I don't need it to parse as a URL, just have it not crash. It's
actually a marker for a reference in an academic paper so missing it is the
correct action.
