### ISSUE TITLE
[Bug] IPv4Address object has no attribute split

### ISSUE THREAD

**Issue by supernothing** [lipoja/URLExtract#41]
## Issue

Ran into this issue when on v0.10 running this over a large sample of strings. I believe it has something to do with having a domain nested in the URL.

```
'IPv4Address' object has no attribute 'split'
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.6/site-packages/urlextract/urlextract_core.py", line 568, in find_urls
    return list(urls)
  File "/usr/local/lib/python3.6/site-packages/urlextract/urlextract_core.py", line 542, in gen_urls
    tmp_url = self._complete_url(text, offset + tld_pos, tld)
  File "/usr/local/lib/python3.6/site-packages/urlextract/urlextract_core.py", line 351, in _complete_url
    if not self._is_domain_valid(complete_url, tld):
  File "/usr/local/lib/python3.6/site-packages/urlextract/urlextract_core.py", line 438, in _is_domain_valid
    host_parts = host.split('.')
AttributeError: 'IPv4Address' object has no attribute 'split'
```

## Steps to reproduce
Below is a minimal test case:

```python
import urlextract
urlextract.URLExtract().find_urls("http://0.0.0.0/a.io")
```

**Comment by lipoja** [comment]
Thank you for that detailed report. I will have a look on it.

**Comment by lipoja** [comment]
This issue is fixed in version 0.13.0

**Comment by warezers** [comment]
I updated version 0.13.0 but I get the same error 
```
from urlextract import URLExtract
extractor = URLExtract()
urls_unique = set()
files = "/Users/roc/Desktop/WEB_000.w3c"
with open(files, 'r', encoding='utf-8') as f:
    for line in f:
        urls = extractor.find_urls(line, only_unique=True)
        urls_unique |= set(urls)
print(urls_unique)
```


```
Traceback (most recent call last):
  File "/Users/roc/PycharmProjects/implace/testrun.py", line 657, in <module>
    for url in extractor.find_urls(line):
  File "/Users/roc/Library/Python/3.6/lib/python/site-packages/urlextract/urlextract_core.py", line 636, in find_urls
    return list(urls)
  File "/Users/roc/Library/Python/3.6/lib/python/site-packages/urlextract/urlextract_core.py", line 598, in gen_urls
    tmp_url = self._complete_url(text, offset + tld_pos, tld)
  File "/Users/roc/Library/Python/3.6/lib/python/site-packages/urlextract/urlextract_core.py", line 376, in _complete_url
    if not self._is_domain_valid(complete_url, tld):
  File "/Users/roc/Library/Python/3.6/lib/python/site-packages/urlextract/urlextract_core.py", line 483, in _is_domain_valid
    host_parts = host.split('.')
AttributeError: 'IPv4Address' object has no attribute 'split'
```

**Comment by lipoja** [comment]
@warezers Could you double check that you are running version 0.13.0? Because from the Traceback I see that it failed on line 483 on host.split('.'). But in latest version the line 483 is empty.

**Comment by warezers** [comment]
@lipoja yes, new update version is working
thank you
